{{- $fullName := include "ddl-verification-controller.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  VERIFICATIONCONTROLLER_MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  VERIFICATIONCONTROLLER_MONGODB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  VERIFICATIONCONTROLLER_AGENT_RECIPIENTKEY: {{ .Values.agent.verkey | default ""| b64enc | quote }}
  VERIFICATIONCONTROLLER_AGENT_APIKEY: {{ .Values.agent.APIKey | default "" | b64enc | quote }}
  VERIFICATIONCONTROLLER_APIKEY: {{ .Values.APIKey | default "" | b64enc | quote }}
