apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddl-verification-controller.fullname" . }}
  labels:
    {{- include "ddl-verification-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    {{- include "ddl-verification-controller.selectorLabels" . | nindent 4 }}
