version: '2'
services:
  verification-controller-mongodb:
    image: mongo:4.2.7
    ports:
      - '27018:27017'
    command: mongos --configdb csvr/verificationcontroller-mongodb-config --bind_ip 0.0.0.0
  verification-controller-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --shardsvr --replSet rs1
  verification-controller-mongodb-config:
    image: mongo:4.2.7
    container_name: verificationcontroller-mongodb-config
    command: mongod --configsvr --dbpath /data/db --replSet csvr
